<form class="log-in-form"
action="<?=App::config('url')?>login/autoriziraj"
method="POST">
<h4 class="text-center">Autorizacija</h4>
  <label>
    <input type="email" name="email" placeholder="Email"
    value="<?=$email?>" />
  </label>
  <label>
    <input type="password" name="lozinka" placeholder="Lozinka" />
  </label>
  <p>
    <input type="submit" class="button expanded" value="Prijava" />
  </p>
  <?=$poruka?>
</form>